<a href="https://colab.research.google.com/github/brysonjohnson0/Retail-Sales-SQL-Analysis/blob/main/Retail_Sales_SQL_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Import Libraries

In [ ]:
import pandas as pd
import sqlite3

# Load Dataset

In [ ]:
df = pd.read_excel("/SampleSuperstore Raw Data.xlsx")

# Create SQLite Dataset

In [ ]:
import sqlite3
conn = sqlite3.connect("RetailSales.db")

In [ ]:
pd.read_sql("SELECT * FROM sales LIMIT 5;", conn)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Segment,Country,City,State,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,2016-11-08 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,2016-11-08 00:00:00,2016-11-11 00:00:00,Second Class,CG-12520,Consumer,United States,Henderson,Kentucky,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,2016-06-12 00:00:00,2016-06-16 00:00:00,Second Class,DV-13045,Corporate,United States,Los Angeles,California,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,2015-10-11 00:00:00,2015-10-18 00:00:00,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,2015-10-11 00:00:00,2015-10-18 00:00:00,Standard Class,SO-20335,Consumer,United States,Fort Lauderdale,Florida,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

# SQL Analysis

##**Business Question 1**

Which products generated the highest total sales revenue?

This analysis identifies the company's top-performing products based on total revenue.

In [ ]:
query= """
SELECT
   "Product Name" AS Product,
   ROUND(SUM(Sales),2) AS Total_Sales
FROM sales
GROUP BY "Product Name"
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

                                             Product  Total_Sales
0              Canon imageCLASS 2200 Advanced Copier     61599.82
1  Fellowes PB500 Electric Punch Plastic Comb Bin...     27453.38
2  Cisco TelePresence System EX90 Videoconferenci...     22638.48
3       HON 5400 Series Task Chairs for Big and Tall     21870.58
4         GBC DocuBind TL300 Electric Binding System     19823.48
5   GBC Ibimaster 500 Manual ProClick Binding System     19024.50
6               Hewlett Packard LaserJet 3310 Copier     18839.69
7  HP Designjet T520 Inkjet Large Format Printer ...     18374.90
8          GBC DocuBind P400 Electric Binding System     17965.07
9        High Speed Automatic Electric Letter Opener     17030.31

###Findings
Canon imageCLASS 2200 Advanced Copier was the top-selling product.
The top 10 products contributed a significant portion of total revenue.

###Business Insight

High-performing products should be monitored closely for inventory planning, pricing strategy, and promotional opportunities.

## **Business Question 2**

Which region generated the highest total sales?

Understanding regional performance helps identify where the business generates the most revenue.

In [ ]:
query= """
SELECT
   Region,
   ROUND(SUM(Sales),2) AS Total_Sales
FROM Sales
GROUP BY Region
ORDER BY Total_Sales DESC
LIMIT 5;
"""

pd.read_sql(query, conn)

    Region  Total_Sales
0     West    725457.82
1     East    678781.24
2  Central    501239.89
3    South    391721.91

##Findings
The West region generated the highest sales.
The South generated the lowest sales.

##Business Insight

The West represents the company's strongest market. Lower-performing regions could benefit from targeted marketing campaigns or operational improvements.

## **Busines Question 3**

Which customers generated the highest total sales?

This analysis compares sales performance across the company's top customer's.

In [ ]:
query= """
SELECT
   "Customer ID",
   ROUND(SUM(Sales),2) AS Total_Sales
FROM Sales
GROUP BY "Customer ID"
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

  Customer ID  Total_Sales
0    SM-20320     25043.05
1    TC-20980     19052.22
2    RB-19360     15117.34
3    TA-21385     14595.62
4    AB-10105     14473.57
5    KL-16645     14175.23
6    SC-20095     14142.33
7    HL-15040     12873.30
8    SE-20110     12209.44
9    CC-12370     12129.07

##Findings
A relatively small group of customers generated the highest sales.

##Business Insight

These customers may represent strategic accounts. Customer retention efforts and personalized engagement could help maintain long-term revenue.

## **Business Question 4**

Which product categories generated the most sales?

This analysis compares sales performance across the company's primary product categories.

In [ ]:
query= """
SELECT
   Category,
   ROUND(SUM(Sales),2) AS Total_Sales
FROM Sales
GROUP BY Category
ORDER BY Total_Sales DESC;
"""

pd.read_sql(query, conn)

          Category  Total_Sales
0       Technology    836154.03
1        Furniture    741999.80
2  Office Supplies    719047.03

##Findings
Technology generated the highest sales.
Furniture ranked second.
Office Supplies ranked third.

##Business Insight

Technology appears to be the company's strongest revenue category. Future analysis could compare sales with profitability to determine whether high sales also translate into strong margins.

## **Business Question 5**

What does the company's monthly trend in revenue look like?

This analysis compares sales performance month-to-month.

In [ ]:
query= """
SELECT
   strftime('%Y-%m', "Order Date") AS Month,
   ROUND(SUM(Sales),2) AS Total_Sales
FROM Sales
GROUP BY Month
ORDER BY Month;
"""

pd.read_sql(query, conn)

      Month  Total_Sales
0   2014-01     14236.90
1   2014-02      4519.89
2   2014-03     55691.01
3   2014-04     28295.35
4   2014-05     23648.29
5   2014-06     34595.13
6   2014-07     33946.39
7   2014-08     27909.47
8   2014-09     81777.35
9   2014-10     31453.39
10  2014-11     78628.72
11  2014-12     69545.62
12  2015-01     18174.08
13  2015-02     11951.41
14  2015-03     38726.25
15  2015-04     34195.21
16  2015-05     30131.69
17  2015-06     24797.29
18  2015-07     28765.33
19  2015-08     36898.33
20  2015-09     64595.92
21  2015-10     31404.92
22  2015-11     75972.56
23  2015-12     74919.52
24  2016-01     18542.49
25  2016-02     22978.82
26  2016-03     51715.88
27  2016-04     38750.04
28  2016-05     56987.73
29  2016-06     40344.53
30  2016-07     39261.96
31  2016-08     31115.37
32  2016-09     73410.02
33  2016-10     59687.75
34  2016-11     79411.97
35  2016-12     96999.04
36  2017-01     43971.37
37  2017-02     20301.13
38  2017-03     58872.35
39  2017-04     36521.54
40  2017-05     44261.11
41  2017-06     52981.73
42  2017-07     45264.42
43  2017-08     63120.89
44  2017-09     87866.65
45  2017-10     77776.92
46  2017-11    118447.83
47  2017-12     83829.32

##Findings
Sales fluctuated throughout the year.
Overall revenue increased over the four-year period.

##Business Insight

The company experienced long-term growth while also showing seasonal fluctuations. Understanding these trends can support forecasting and inventory planning.

## **Business Question 6**

Which year did the company generate the most revenue?

This analysis compares sales performance year-to-year.

In [ ]:
query= """
SELECT
   strftime('%Y', "Order Date") AS Year,
   ROUND(SUM(Sales),2) AS Total_Sales
FROM Sales
GROUP BY Year
ORDER BY Year;
"""

pd.read_sql(query, conn)

   Year  Total_Sales
0  2014    484247.50
1  2015    470532.51
2  2016    609205.60
3  2017    733215.26

##Findings
2017 generated the highest annual sales.
Sales generally increased from 2014 through 2017.

##Business Insight

The steady upward trend suggests sustained business growth. Additional data would be needed to determine what factors contributed to the growth.

## **Business Question 7**

Which customer segment generated the most revenue?

This analysis compares which customer groups contributed the most revenue.

In [ ]:
query= """
SELECT
   Segment,
   ROUND(SUM(Sales),2) AS Total_Sales
FROM Sales
GROUP BY Segment
ORDER BY Segment;
"""

pd.read_sql(query, conn)

       Segment  Total_Sales
0     Consumer   1161401.34
1    Corporate    706146.37
2  Home Office    429653.15

##Findings
Consumer was the highest-revenue segment.
Home Office generated the lowest revenue.

##Business Insight

The Consumer segment should remain a key focus for marketing and customer retention. At the same time, the Home Office segment may present opportunities for targeted growth initiatives.

## **Business Question 8**

Which states generated the highest sales revenue?

This analysis compares which states contributed the most revenue.

In [ ]:
query= """
SELECT
   State,
   ROUND(SUM(Sales),2) AS Total_Sales
FROM Sales
GROUP BY State
ORDER BY Total_Sales DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

          State  Total_Sales
0    California    457687.63
1      New York    310876.27
2         Texas    170188.05
3    Washington    138641.27
4  Pennsylvania    116511.91
5       Florida     89473.71
6      Illinois     80166.10
7          Ohio     78258.14
8      Michigan     76269.61
9      Virginia     70636.72

##Findings
California generated the highest sales.
New York ranked second.
Texas ranked third.

##Business Insight

These states represent major revenue markets and should remain priorities for sales strategy, customer engagement, and resource allocation.

## **Business Question 9**

Which states generated the highest total profit?

This analysis compares which states contributed the most profit.

In [ ]:
query= """
SELECT
   State,
   ROUND(SUM(Profit),2) AS Profit
FROM Sales
GROUP BY State
ORDER BY Profit DESC
LIMIT 10;
"""

pd.read_sql(query, conn)

        State    Profit
0  California  76381.39
1    New York  74038.55
2  Washington  33402.65
3    Michigan  24463.19
4    Virginia  18597.95
5     Indiana  18382.94
6     Georgia  16250.04
7    Kentucky  11199.70
8   Minnesota  10823.19
9    Delaware   9977.37

##Findings
California generated the highest total profit.
New York ranked second.
Washington ranked third.

##Business Insight

Comparing sales and profit by state helps identify markets that not only generate high revenue but also contribute strong profitability. This distinction is valuable when making investment and expansion decisions.

# **Retail Sales SQL Analysis**
## Portfolio Project

**Author:** Bryson Johnson

**Tools/Skills Used:**
- Python
- Pandas
- SQLite
- SQL
- Google Colab
- Data Aggregation
- Business Analysis
- Time-Series Analysis
- Data Visualization Preparation

### Project Objective

Analyze a retail sales dataset using SQL to identify trends in sales, profit, customer segments, products, and regional performance. The goal is to answer business questions that support data-driven decision making.

### Key Findings

- Technology was the highest-performing product category. -Continue investing efforts.
- Consumer customers generated the most revenue. - Maintain focus on consumer segment while exploring oppurtunites to help home office sales grow.
- California produced the highest sales and profit. -Prioritize.
- Sales increased steadily from 2014 through 2017.
- Regional analysis identified the West as the strongest-performing market.